(setenv "WORKON_HOME" user-conda-env-directory)
(add-hook 'eshell-mode-hook 'pyvenv-mode)
(pyvenv-workon user-conda-env-name)
(venv-initialize-interactive-shells)
(venv-initialize-eshell)
(setq-default indent-tabs-mode nil)
(add-to-list 'auto-mode-alist '("\\.py\\'" . elpy-mode))
(setq elpy-shell-echo-input nil)
(setq python-shell-completion-native-enable nil)
(setq elpy-rpc-virtualenv-path 'current)
(conda-env-initialize-eshell)
;(add-to-list 'auto-mode-alist '("\\.py\\'" . conda-env-autoactivate-mode))
(conda-env-autoactivate-mode t)
(setq conda-env-home-directory (expand-file-name user-conda-directory))
(custom-set-variables '(conda-anaconda-home user-conda-directory))
