(setenv "WORKON_HOME" user-conda-env-directory)
(pyvenv-mode 1)
(pyvenv-workon user-conda-env-name)
(venv-initialize-interactive-shells)
(venv-initialize-eshell)
(elpy-enable)
(setq python-shell-completion-native-enable nil)
(setq elpy-rpc-virtualenv-path 'current)
(conda-env-initialize-eshell)
(conda-env-autoactivate-mode t)
(setq conda-env-home-directory (expand-file-name user-conda-directory))
(custom-set-variables '(conda-anaconda-home user-conda-directory))
