(defun set-prog-lang (lang)
  (interactive)
  (setq prog-lang lang)
  )

(defun my-compile ()
  (interactive)
    (setq program-file-name (file-name-nondirectory buffer-file-name))
  (setq java-file-name-no-extension (replace-regexp-in-string ".java" "" program-file-name))
  (setq python-file-name-no-extension (replace-regexp-in-string ".py" "" program-file-name))
  (setq cpp-file-name-no-extension (replace-regexp-in-string ".cpp" "" program-file-name))
  
  (if (equal prog-lang "java")
      (compile-java)
      )
  (if (equal prog-lang "python")
      (my-run-python)
    )
  (if (equal prog-lang "cpp")
     (compile-cpp)
    )
  )

(defun my-run ()
  (interactive)
    (setq program-file-name (file-name-nondirectory buffer-file-name))
  (setq java-file-name-no-extension (replace-regexp-in-string ".java" "" program-file-name))
  (setq python-file-name-no-extension (replace-regexp-in-string ".py" "" program-file-name))
  (setq cpp-file-name-no-extension (replace-regexp-in-string ".cpp" "" program-file-name))

  (if (equal prog-lang "java")
      (run-java)
      )
  (if (equal prog-lang "python")
      (my-run-python)
    )
  (if (equal prog-lang "cpp")
      (run-cpp)
    )
  )


(add-hook 'java-mode-hook (lambda () (set-prog-lang "java")))
(add-hook 'python-mode-hook (lambda () (set-prog-lang "python")))
(add-hook 'c++-mode-hook (lambda () (set-prog-lang "cpp")))


;; ~~~~~~~~~~~~~~~~~~~~~~~~ Python ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(defun my-run-python ()
  (interactive)
  (setq eshell-directory default-directory)
  (eshell)
  
  (insert "quit()")
  (execute-kbd-macro (read-kbd-macro "<return>"))
  (sit-for 1)
      (cd eshell-directory)
      (execute-kbd-macro (read-kbd-macro "<return>"))
  (insert "ipython -i ")
    (insert program-file-name)
    (execute-kbd-macro (read-kbd-macro "<return>"))
    )
;; ~~~~~~~~~~~~~~~~~~~~~~~~~~ Java ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(defun compile-java ()
    (interactive)
    (setq eshell-directory default-directory)
      (eshell)
      (cd eshell-directory)
      (execute-kbd-macro (read-kbd-macro "<return>"))
    (insert "javac ")
    (insert program-file-name)
    (execute-kbd-macro (read-kbd-macro "<return>"))
    (popwin:stick-popup-window)
    (other-window -1)
    )
    

(defun run-java ()
  (interactive)
  (eshell)
  (delete-window)
  (eshell)
    (insert "java ")
    (insert java-file-name-no-extension)
    (execute-kbd-macro (read-kbd-macro "<return>"))
    )

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~ cpp ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(defun compile-cpp ()
    (interactive)
    (setq eshell-directory default-directory)
      (eshell)
      (cd eshell-directory)
      (execute-kbd-macro (read-kbd-macro "<return>"))
      (insert (concat "g++ -o " cpp-file-name-no-extension))
      (insert " ")
    (insert program-file-name)
    (execute-kbd-macro (read-kbd-macro "<return>"))
    (popwin:stick-popup-window)
    (other-window -1)
    )
    

(defun run-cpp ()
  (interactive)
  (eshell)
  (delete-window)
  (eshell)
    (insert "./")
    (insert cpp-file-name-no-extension)
    (insert ".exe")
    (execute-kbd-macro (read-kbd-macro "<return>"))
    )
