(setenv "WORKON_HOME" user-conda-env-directory)
(add-hook 'eshell-mode-hook 'pyvenv-mode)
(pyvenv-workon user-conda-env-name)
(venv-initialize-interactive-shells)
(venv-initialize-eshell)
(setq python-shell-interpreter "python")
(setq-default indent-tabs-mode t)
(setq elpy-shell-echo-input nil)
(setq python-shell-completion-native-enable nil)
(setq elpy-rpc-virtualenv-path 'current)
